server:
  port: 80
  context-path: /

## 下面的数据库和redis需要填写你自己的

#spring:
#    datasource:
#      url: jdbc:mysql://116.196.66.248:3306/duilu_core?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: jlyc123#@!
#      driverClassName: com.mysql.jdbc.Driver
